name: Publish

on:
    push:
        tags:
            - 'v*'

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            id-token: write

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 22
                  cache: npm
                  registry-url: https://registry.npmjs.org

            - uses: dopplerhq/secrets-fetch-action@v2.0.0
              with:
                  doppler-token: ${{ secrets.DOPPLER_TOKEN }}
                  inject-env-vars: true

            - run: npm ci

            - run: npm publish --provenance --access public
