name: Publish

on:
    push:
        tags:
            - 'v*'

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            id-token: write

        steps:
            - uses: actions/checkout@v4
              with:
                  fetch-depth: 0

            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: npm
                  registry-url: https://registry.npmjs.org

            - uses: dopplerhq/secrets-fetch-action@v1.3.0
              with:
                  doppler-token: ${{ secrets.DOPPLER_TOKEN }}
                  inject-env-vars: true

            - run: npm ci

            - run: npm run fmt:check

            - run: npm run tc

            - run: npm run lint

            - run: npm run test:coverage

            - run: npm publish --provenance --access public
